#!/bin/sh
# /linuxrc

nfs_dirs='/bin /etc /lib/ /sbin/ /usr'
dirs_to_copy='/home /mnt /root /run /var'
dirs_to_create='/dev /proc /sys /oldroot /tmp'
noderoot=/noderoot
nfs_server=192.168.1.160
nfs_basedir=/mnt/media/thinclient/base

if [ ! -d "$noderoot" ]; then
  echo "$noderoot does not exist. Create it on the base image"
  exit 101
fi

echo "Mount tmpfs"
mount -t tmpfs none $noderoot

for dir in $dirs_to_create; do
  echo "Checking if $noderoot$dir exists"
    if [ ! -d "$noderoot$dir" ]; then
      echo "Creating $noderoot$dir"
      mkdir $noderoot$dir
    fi
done

echo "Mounting new $noderoot/proc"
mount -t proc none $noderoot/proc

echo "Mounting new $noderoot/sys"
mount -t sysfs none $noderoot/sys

echo "Mounting new $noderoot/dev"
mount -o bind /dev $noderoot/dev

for dir in $dirs_to_copy; do
  echo "Copying $dir to $noderoot"
  cp -a $dir $noderoot
done

for dir in $nfs_dirs; do
  if [ ! -d "$noderoot$dir" ]; then
    echo "Creating $noderoot$dir"
    mkdir $noderoot$dir
  fi

  echo "Mounting nfs dir $dir"
  mount -t nfs $nfs_server:$nfs_basedir$dir $noderoot$dir -o nolock,ro
done

echo "running pivot_root"
cd $noderoot
pivot_root . ./oldroot

echo "Unmounting old root"
umount -l /oldroot

if [ `mountpoint /oldroot/ > /dev/null; echo $?` -eq 1 ]; then
  #Not a mountpoint anymore
  echo "Removing /oldroot directory"
  rm -r /oldroot
fi

# redirect to stderr because of "start: failed to connect to socket /com/ubuntu/upstart"
# or should I use a custom init script?
echo "Regenerating openssh keys"
/usr/sbin/dpkg-reconfigure openssh-server 2> /dev/null

echo "Clearing display"
#clear

# At this point $noderoot/etc/fstab is very important!
# https://help.ubuntu.com/community/DisklessUbuntuHowto (6. configure fstab)

echo "Starting normal boot process"
exec /sbin/init <dev/console >dev/console 2>&1
