#!/bin/sh
# /linuxrc

if [ ! -d "/tmpfs" ]; then
  mkdir /tmpfs
fi

echo "Mount tmpfs"
mount -t tmpfs none /tmpfs

if [ ! -d "/tmpfs/proc" ]; then
  mkdir /tmpfs/proc
fi

if [ ! -d "/tmpfs/sys" ]; then
  mkdir /tmpfs/sys
fi

if [ ! -d "/tmpfs/oldroot" ]; then
  mkdir /tmpfs/oldroot
fi


echo "Copying /dev to tmpfs"
cp -a /dev /tmpfs/
echo "Copying /bin to tmpfs"
cp -a /bin /tmpfs/
echo "Copying /sbin to tmpfs"
cp -a /sbin /tmpfs/
echo "Copying /etc to tmpfs"
cp -a /etc /tmpfs/
echo "Copying /usr to tmpfs"
cp -a /usr /tmpfs/
echo "Copying /home to tmpfs"
cp -a /home /tmpfs/
echo "Copying /lib to tmpfs"
cp -a /lib /tmpfs/
echo "Copying /root to tmpfs"
cp -a /root /tmpfs/
echo "Copying /var to tmpfs"
cp -a /var /tmpfs/


echo "Pivot_root"
#umount /proc
#chroot /tmpfs
cd /tmpfs
pivot_root . ./oldroot

#umount /oldroot
#rm -r /oldroot

#mount none /proc -t proc
#mount none /dev -t devfs

echo "Clearing display"
clear

# At this point /tmpfs/etc/fstab is very important!
# https://help.ubuntu.com/community/DisklessUbuntuHowto (6. configure fstab)

# Execute normal boot procedure
exec /sbin/init
